/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dragon_opengles01_ndk_NDKTest */

#ifndef _Included_com_dragon_opengles01_ndk_NDKTest
#define _Included_com_dragon_opengles01_ndk_NDKTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dragon_opengles01_ndk_NDKTest
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dragon_opengles01_ndk_NDKTest_hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
